export type { default as GetPostsResponse } from "./axios-request/getPostsResponse"
export type { default as GetCategoriesResponse } from "./axios-request/getCategoriesResponse"
export type { default as GetWidgetResponse } from "./axios-request/getWidgetResponse"
export type { default as GraphqlGetRecentPostsResponse } from "./graphql-request/getRecentPostsResponse"
export type { default as GraphqlGetFeaturedPostsResponse } from "./graphql-request/getFeaturedPostsResponse"
export type { default as GraphqlGetPopularPostsResponse } from "./graphql-request/getPopularPostsResponse"
export type { default as GraphqlGetWidgetResponse } from "./graphql-request/getWidgetResponse"
export type { default as GraphqlGetCategoriesResponse } from "./graphql-request/getCategoriesResponse"
