/* eslint-disable prettier/prettier */
import Head from "next/head"
import axios, { AxiosResponse, AxiosError } from "axios"
import useSWR, { Key, Fetcher } from "swr"
import { useRouter } from "next/router"

type APIResponse = {
  data: Data
}

type Data = {
  page: Page
}

type Page = {
  content: string
  title: string
}

type Config = {
  timeout: number
}

const Home: React.FC = () => {
  const router = useRouter()
  const {
    query: { slug }
  } = router
  const API_URL: Key = `api/page/${slug}`
  const fetcher: Fetcher<APIResponse, string> = (path) =>
    axios
      .get<APIResponse, AxiosResponse<APIResponse, AxiosError>, Config>(path, {
        timeout: 10000
      })
      .then((res) => res.data)

  const { data, error } = useSWR<APIResponse, Error>(API_URL, fetcher)

  if (error) {
    return <div>error...</div>
  }

  if (!data) {
    return <div>loading...</div>
  }

  const title = data.data.page.title
  const content = data.data.page.content

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <div dangerouslySetInnerHTML={{ __html: content }}></div>
      </main>
    </div>
  )
}

export default Home
